#!/usr/bin/env sh
set -e
usage() {
    echo "tw [OPTION] NAME
Command line utility for create and keeping organized large LaTeX documents.

OPTION
    init                Copy default template and style to current directory.
    new-section         Create new subsection file in subfiles/NAME.tex
    update-cls          Change the default 'custom.cls' style file.
    latest-section      View or Edit the latest saved section.
   "
}

[ -z "$2" ] && usage && exit 1
[ "$3" ] && echo "WARNING: Multiple arguments provided. Maybe you forgot to
\"quote\" NAME."

TW_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# Custom configs
AUTHOR=$USER    # Default author name
TITLE="$2"      # Default section/file title
FILENAME=$(echo "$2" | sed -e 's/\(.*\)/\L\1/g' -e 's/\s\+/_/g') # 'Test Title' => 'test_title'

case $1 in
    new-section)
        mkdir -p $PWD/subfiles/
        cp -i $TW_DIR/subfiles/subtemplate.tex $PWD/subfiles/$FILENAME.tex

        # Set custom section title  (TODO: Assure no / in $2)
        sed -i "s/First Section/$2/" $PWD/subfiles/$FILENAME.tex
        echo "Done. remember to add '\\subfile{subfiles/$FILENAME}' to your main .tex file"
        ;;

    init)
        cp -i $TW_DIR/custom.cls $PWD
        cp -i $TW_DIR/template.tex $PWD/$FILENAME.tex

        # Change default author and title
        sed -i -e "s/{author}/{$AUTHOR}/" \
               -e "s/{title}/{$TITLE}/" \
               $PWD/$FILENAME.tex
        ;;

    update-cls)
        cp -i "$2" $TW_DIR/custom.cls
        ;;

    latest-section)
        [ ! -d "subfiles" ] && echo "Unable to find 'subfiles' directory" && exit 1
        LATEST_EDIT=$(ls -t1 subfiles/*.tex | head -n1)

        case "$2" in
            open|edit) $EDITOR $LATEST_EDIT;;
            name|print|view) echo $LATEST_EDIT;;
            *) echo "Only [edit|view] are allowed."
        esac
        ;;
    *)
        usage
        exit 1
esac
